#79 cargar pdf storage
ANP-2020A/proyecto-semestre-titulacionESFOT pull request #80
Opened 2021-04-06 17:10 UTC by NicoleZambrano02

2021-04-06 23:35 UTC, KevinJ1998 commented on app/Http/Controllers/ProjectController.php
> -            'title' => 'string|unique:projects,title,' . $project->id . '|max:255',
vuelve a dejar esta línea @NicoleZambrano02 que es para que el titulo sea único

2021-04-06 23:37 UTC, KevinJ1998 requested changes
Revisa el comentario en el archivo ProjectController

2021-04-07 13:09 UTC, jon2013p approved these changes

2021-04-07 23:10 UTC, KevinJ1998 approved these changes

2021-04-07 23:10 UTC, merged